name: todo_with_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.1
  lottie: ^2.7.0
  flutter_slidable: ^3.0.0
  google_nav_bar: ^5.0.6
  go_router: ^11.1.2
  flutter_local_notifications: ^16.1.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  bottom_navy_bar: ^6.0.0

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: 3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

